spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172
  
server:
  port: 30090
  
logging:
  file: /usr/local/data/apollo/logs/apollo-adminservice.log
